DROP TABLE IF EXISTS "CouponCardObjects" CASCADE;
DROP TABLE IF EXISTS "CoordinatorObjects" CASCADE;
DROP TABLE IF EXISTS "StudentObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_StudentObjects_kollelType";
DROP TABLE IF EXISTS "SupportRecommendationObjects" CASCADE;
DROP TABLE IF EXISTS "DocumentObjects" CASCADE;
DROP TABLE IF EXISTS "NeedyObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_maritalStatus";
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_type";
DROP TABLE IF EXISTS "OrganizationObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_OrganizationObjects_type";
DROP TABLE IF EXISTS "UserObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_UserObjects_role";
DROP TABLE IF EXISTS "UserObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_UserObjects_role";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_UserObjects_role' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_UserObjects_role"; CREATE TYPE "public"."enum_UserObjects_role" AS ENUM('מנהל', 'רכז', 'וועדת רווחה', 'מחלקת רווחה');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "UserObjects" ("id"   SERIAL , "username" VARCHAR(255), "password" VARCHAR(255), "role" "public"."enum_UserObjects_role", "firstName" VARCHAR(255), "lastName" VARCHAR(255), "phone" VARCHAR(255), "isActive" INTEGER, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'UserObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "OrganizationObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_OrganizationObjects_type";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_OrganizationObjects_type' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_OrganizationObjects_type"; CREATE TYPE "public"."enum_OrganizationObjects_type" AS ENUM('בית כנסת', 'בית חב''''ד', 'כולל', 'קהילה 
מקומית', 'נציג הקונגרס', 'מועדונית נשים', 'אחר');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "OrganizationObjects" ("id"   SERIAL , "name" VARCHAR(255), "address" VARCHAR(255), "city" VARCHAR(255), "type" "public"."enum_OrganizationObjects_type", "organizationNo" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'OrganizationObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "NeedyObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_maritalStatus";
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_type";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_NeedyObjects_maritalStatus' GROUP BY 1
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_NeedyObjects_type' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_maritalStatus"; CREATE TYPE "public"."enum_NeedyObjects_maritalStatus" AS ENUM('נשוי', 'רווק', 'גרוש', 'אלמן');
DROP TYPE IF EXISTS "public"."enum_NeedyObjects_type"; CREATE TYPE "public"."enum_NeedyObjects_type" AS ENUM('אברך', 'נתמך מחלקת רווחה', 'נתמך קמחא דפסחא');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "NeedyObjects" ("id"   SERIAL , "ssn" VARCHAR(255), "firstName" VARCHAR(255), "lastName" VARCHAR(255), "phone" VARCHAR(255), "mobilePhone" VARCHAR(255), "address" VARCHAR(255), "city" VARCHAR(255), "numberOfPersons" INTEGER, "maritalStatus" "public"."enum_NeedyObjects_maritalStatus", "type" "public"."enum_NeedyObjects_type", "description" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "creatorId" INTEGER REFERENCES "UserObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "organizationId" INTEGER REFERENCES "OrganizationObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'NeedyObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "DocumentObjects" CASCADE;
CREATE TABLE IF NOT EXISTS "DocumentObjects" ("id"   SERIAL , "fileName" VARCHAR(255), "doc" bytea, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "needyId" INTEGER REFERENCES "NeedyObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'DocumentObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "PaymentObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_PaymentObjects_type";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_PaymentObjects_type' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_PaymentObjects_type"; CREATE TYPE "public"."enum_PaymentObjects_type" AS ENUM('כרטיס', 'העברה בנקאית', 'שיק', 'אחר');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "PaymentObjects" ("id"   SERIAL , "date" TIMESTAMP WITH TIME ZONE, "amount" INTEGER, "type" "public"."enum_PaymentObjects_type", "receiver" VARCHAR(255), "serialNumber" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "needyId" INTEGER REFERENCES "NeedyObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "receiverSignatureDocId" INTEGER REFERENCES "DocumentObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "userEnterId" INTEGER REFERENCES "UserObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'PaymentObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "SupportRecommendationObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_SupportRecommendationObjects_recommenderType";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_SupportRecommendationObjects_recommenderType' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_SupportRecommendationObjects_recommenderType"; CREATE TYPE "public"."enum_SupportRecommendationObjects_recommenderType" AS ENUM('מנהל', 'רכז', 'וועדת רווחה', 'מחלקת רווחה');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "SupportRecommendationObjects" ("id"   SERIAL , "sum" INTEGER, "recommendDate" TIMESTAMP WITH TIME ZONE, "recommenderType" "public"."enum_SupportRecommendationObjects_recommenderType", "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "needyId" INTEGER REFERENCES "NeedyObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "recommenderId" INTEGER REFERENCES "UserObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SupportRecommendationObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "StudentObjects" CASCADE;
DROP TYPE IF EXISTS "public"."enum_StudentObjects_kollelType";
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_StudentObjects_kollelType' GROUP BY 1
DROP TYPE IF EXISTS "public"."enum_StudentObjects_kollelType"; CREATE TYPE "public"."enum_StudentObjects_kollelType" AS ENUM('יום שלם', 'חצי יום');
WITH ranges AS (  SELECT pg_range.rngtypid, pg_type.typname AS rngtypname,         pg_type.typarray AS rngtyparray, pg_range.rngsubtype    FROM pg_range LEFT OUTER JOIN pg_type ON pg_type.oid = pg_range.rngtypid)SELECT pg_type.typname, pg_type.typtype, pg_type.oid, pg_type.typarray,       ranges.rngtypname, ranges.rngtypid, ranges.rngtyparray  FROM 
pg_type LEFT OUTER JOIN ranges ON pg_type.oid = ranges.rngsubtype WHERE (pg_type.typtype IN('b', 'e'));
CREATE TABLE IF NOT EXISTS "StudentObjects" ("id"   SERIAL , "kollelName" VARCHAR(255), "headOfTheKollelName" VARCHAR(255), "headOfTheKollelPhone" VARCHAR(255), "kollelType" "public"."enum_StudentObjects_kollelType", "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "needyId" INTEGER REFERENCES "NeedyObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'StudentObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "CoordinatorObjects" CASCADE;
CREATE TABLE IF NOT EXISTS "CoordinatorObjects" ("id"   SERIAL , "ssn" VARCHAR(255), "address" VARCHAR(255), "city" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "userId" INTEGER REFERENCES "UserObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "organizationId" INTEGER REFERENCES "OrganizationObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'CoordinatorObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
DROP TABLE IF EXISTS "CouponCardObjects" CASCADE;
CREATE TABLE IF NOT EXISTS "CouponCardObjects" ("id" INTEGER , "value" INTEGER, "serialNumber" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "paymentId" INTEGER REFERENCES "PaymentObjects" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'CouponCardObjects' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;